# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ created , edited]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    name: Create release artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
      
      # Setup node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with: 
          node-version: 10.x

      # install NPM
      - name: Run npm ci
        run: npm ci

      # gulp bundle and package solution
      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      # Upload artifacts (sppkg file)
      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: package
          path: sharepoint/solution/${{ env.SPPKG_FILE_NAME }}
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: 'https://uploads.github.com/repos/threewill/archived-comments-webpart/releases/${{ github.ref }}/assets' # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./package.zip
          asset_name: package.zip
          asset_content_type: application/zip  
